version: '3.8'

services:
  dsa-lab:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./temp:/tmp/code-exec
    restart: unless-stopped
    mem_limit: 512m
    cpus: '0.5'